/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "#0D1117",
        panel: "#141B29",
        panel2: "#1A2333",
        border: "#26314A",
        "border-soft": "#1D2638",
        text: "#E7ECF6",
        muted: "#8B96AD",
        faint: "#5C6784",
        gold: "#D6A24E",
        "gold-soft": "#3A2F1C",
        "gold-tint": "#D6A24E22",
        "gold-muted": "#D6A24E1A",
        "gold-border": "#D6A24E55",
        blue: "#4C8BF5",
        "blue-soft": "#152744",
        green: "#3FB68B",
        "green-soft": "#123024",
        amber: "#E0A93D",
        "amber-soft": "#332510",
        red: "#E5586B",
        "red-soft": "#331A20",
        purple: "#9A7FE0",
        track: "#232C40",
        disabled: "#3A3F4B",
        overlay: "#00000088",
        "pie-teal": "#5CC8D7",
        "pie-lime": "#B4C46A",
      },
      fontFamily: {
        display: ["Space Grotesk", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
      },
    },
  },
  plugins: [],
}
